### ISSUE TITLE
[Feature Request] Create a folder for each game

### ISSUE THREAD

**Issue by aniscoquelet** [marissa999/decky-recorder#56] opened 2023-06-10 15:32 UTC
I think it'd be nice to be able to have one video folder per game. Would that be hard to do ? 

Thanks for the plugin, it's awesome

**Comment by karasuhebi** [comment] 2023-06-24 01:53
This is a duplicate of #30

**Comment by safijari** [comment] 2023-08-24 23:57
Closing in favor of #30

**Closed by safijari** 2023-08-24 23:57 UTC
